### ISSUE TITLE
Standalone mode for remote control?

### ISSUE THREAD

**Issue by delbonis** [darosior/lightning-qt#10]
Is there an easy way to say, for example, `--standalone --socket=some/ssh/mount/lightning-rpc` and use lightning-qt as a remote control for a c-lightning node running on another machine?

I'm aware there's a roundabout way to remote control nodes with lightning-cli but it'd be nice not to need lightning-cli on the local machine and I'm not sure if lightning-qt is able to run like that.

**Comment by darosior** [comment]
Yes it would work but you would lose the advantages of being a plugin since they have to be registered on startup. Plugin-only functionalities (hooks, notifications) should then have to be conditionally implemented. Does it worth it or should we prefer other "solutions" (such as X11 forwarding maybe) ? Looking forward to have users opinion.

**Comment by delbonis** [comment]
Here's an idea:

Make the plugin part expose a two-way communication interface (maybe a unix socket so you can just use ssh forwarding manually, maybe something else) that provides the node notifications the client needs and connect to that with the client with the actual GUI from wherever the user is.

**Comment by darosior** [comment]
> Make the plugin part expose a two-way communication interface (maybe a unix socket so you can just use ssh forwarding manually, maybe something else) that provides the node notifications the client needs and connect to that with the client with the actual GUI from wherever the user is.

It would however need an user to forward the UNIX socket.

I thought about it and decided to integrate a standalone mode as you first proposed. I'm working on the following scenario : 
- You have lightningd with lightning-qt plugin remotely
- You forward a UNIX domain socket locally
- You `python3 gui.py --socket-path /path/to/socket`

I'll handle notification in a separate manager anyway

**Comment by darosior** [comment]
I added it in https://github.com/darosior/lightning-qt/commit/0dde987ec732651d5234c9681216bc4a040d2512, thank you for your suggestions : I've been wanting to do this since the beginning and you made me do it :D 

Feel free to re open this issue if you have other related requests/questions.
